#!/usr/bin/env python3
# GRIZZLY_TEMPLATE_V1
"""
Generated by Grizzly
"""

def transform(INPUT):
    """Main transformation"""
    OUTPUT = {}
    
    OUTPUT["clientReference"] = INPUT.customerId
    # profile → use module_1 module
    map_module_1(INPUT, OUTPUT)
    
    return OUTPUT

def map_module_1(INPUT, OUTPUT):
    """module_1 mappings"""
    
    OUTPUT["profile"]["contact"] = INPUT.personalInfo.email
