#!/usr/bin/env python3
# GRIZZLY_TEMPLATE_V1
"""
Generated by Grizzly
"""

def map_module_1(INPUT, OUTPUT):
    """module_1 mappings"""
    OUTPUT["profile"]["fullName"] = INPUT.personalInfo.firstName

def transform(INPUT):
    """Main transformation"""
    OUTPUT = {}
    
    OUTPUT["clientReference"] = INPUT.customerId
    # Call module_1 module
    map_module_1(INPUT, OUTPUT)
    
    
    return OUTPUT